#!/bin/bash
# MWAA startup script: set env vars for RAG DAGs (S3 buckets + OpenSearch).
# Generated by Terraform — do not edit by hand; change .tpl and re-apply.

export S3_RAW_BUCKET="${raw_bucket}"
export S3_PROCESSED_BUCKET="${processed_bucket}"
export RAG_OPENSEARCH_HOST="${opensearch_host}"
export RAG_OPENSEARCH_REGION="${aws_region}"
export RAG_OPENSEARCH_INDEX_PREFIX="${opensearch_index_prefix}"
