"""
Talent Intelligence Flow - Main Orchestration

This is the primary flow that orchestrates the entire Talent Intelligence pipeline:
1. Parse job description + ideal candidate description
2. Build baseline profile from Neo4j (current employees in target role)
3. Run diagnostic agent to prioritize attributes
4. Parse applicant resumes (50 max)
5. Build PDL query and search market (50 results)
6. Score all candidates (applicants + market)
7. Run synthesis agent to produce final report
8. Store results with provenance

Role-agnostic: supports any role type, driven by the job description and user configuration.
"""

from typing import List, Dict, Any, Optional, Tuple, Callable
from pydantic import BaseModel, Field
from datetime import datetime, timezone
import uuid
import asyncio

from src.models.talent_analysis import (
    TalentAnalysisResult, CandidateScore, ParsedResume,
    DiagnosticReport, SynthesisReport, BaselineProfile,
    WorkflowProvenanceStep, AnalysisStatus, CandidateSource, PDLQuery,
    ParsedExperience, ParsedEducation
)
from src.services.talent.scoring_engine import MultiDimensionalScoringEngine
from src.services.talent.diagnostic_agent import DiagnosticAgentService, DiagnosticInput
from src.services.talent.synthesis_agent import SynthesisAgentService, SynthesisInput
from src.services.talent.pdl_query_builder import PDLQueryBuilder, PDLQueryParams
from src.services.talent.text_llm_parser import TextLLMParser
from src.services.talent.dynamic_scoring_engine import DynamicScoringEngine
from src.services.talent.enhanced_pdl_query_builder import EnhancedPDLQueryBuilder
from src.services.langfuse_service import get_langfuse_service
from src.core.logging import get_logger, LogCategory
from src.core.config import get_settings

logger = get_logger(__name__, component="talent.flow")
settings = get_settings()


class ApplicantResumeData(BaseModel):
    """Resume data with optional metadata from source system (e.g., Greenhouse)"""
    file_bytes: bytes = Field(description="Raw file content")
    filename: str = Field(description="Original filename")
    # Optional metadata from Greenhouse or other ATS
    greenhouse_id: Optional[int] = Field(default=None, description="Greenhouse candidate ID")
    candidate_name: Optional[str] = Field(default=None, description="Candidate name from ATS")
    candidate_email: Optional[str] = Field(default=None, description="Candidate email from ATS")
    linkedin_url: Optional[str] = Field(default=None, description="LinkedIn URL from ATS")
    phone: Optional[str] = Field(default=None, description="Phone number from ATS")
    location: Optional[str] = Field(default=None, description="Location from ATS")
    
    class Config:
        arbitrary_types_allowed = True


class TalentAnalysisRequest(BaseModel):
    """Input for talent analysis"""
    analysis_id: str = Field(description="Unique analysis ID (generated by API)")
    job_description: str = Field(description="Job description text")
    ideal_candidate_description: str = Field(description="Natural language ideal candidate description")
    # Support both legacy tuple format and new rich format
    applicant_resume_files: List[Any] = Field(default_factory=list, description="List of resume data from current job openings")
    historical_candidate_files: List[Any] = Field(default_factory=list, description="List of resume data from closed/historical job openings (previous candidates)")
    role: Optional[str] = Field(default=None, description="Optional role hint. If not provided, the role is extracted from the job description by the diagnostic agent.")
    customer_id: str = Field(description="Customer ID")
    user_id: int = Field(description="User ID")
    baseline_employee_ids: Optional[List[int]] = Field(default=None, description="Deprecated — baseline now comes from the Career Blueprint")
    baseline_linkedin_urls: Optional[List[str]] = Field(default=None, description="Deprecated — LinkedIn profiles are provided via the Career Blueprint")
    selected_blueprint_id: Optional[int] = Field(default=None, description="Career Blueprint ID — provides baseline from enriched LinkedIn profiles")
    company_dna_id: Optional[int] = Field(default=None, description="ID of company DNA profile to use")
    market_search_limit: Optional[int] = Field(default=None, description="Number of candidates to fetch from market search (overrides config)")


class TalentIntelligenceOrchestrator:
    """
    Main orchestrator for the Talent Intelligence System.
    
    Coordinates all services and agents in the proper sequence.
    """
    
    def __init__(
        self,
        customer_id: str,
        user_id: int,
        pdl_query_limit: Optional[int] = None,
        event_callback: Optional[Callable[[str, str, str, Optional[Dict[str, Any]]], None]] = None,
        blueprint_id: Optional[int] = None,
        company_dna_id: Optional[int] = None,
        neo4j_enabled: bool = False  # Legacy param, kept for backward compat
    ):
        """
        Initialize the orchestrator.
        
        Args:
            customer_id: Customer ID for the analysis
            user_id: User ID requesting the analysis
            pdl_query_limit: Number of candidates to retrieve from PDL (default: from settings)
            event_callback: Optional callback for emitting SSE events (analysis_id, event_type, message, metadata)
            blueprint_id: Optional Career Blueprint ID — provides baseline from enriched LinkedIn profiles
            company_dna_id: Optional Company DNA ID for organizational fit scoring
            neo4j_enabled: Legacy parameter, no longer used (baseline comes from Blueprint)
        """
        self.customer_id = customer_id
        self.user_id = user_id
        self.event_callback = event_callback
        self.blueprint_id = blueprint_id
        self.company_dna_id = company_dna_id
        self.langfuse_service = get_langfuse_service()
        
        # Get PDL query limit from settings if not provided
        if pdl_query_limit is None:
            from src.core.config import get_settings
            settings = get_settings()
            self.pdl_query_limit = settings.ml_talent_pdl_query_limit
        else:
            self.pdl_query_limit = pdl_query_limit
        
        # Initialize services
        self.resume_parser = TextLLMParser()  # text extraction + LLM
        self.pdl_query_builder = PDLQueryBuilder()
        
        # Scoring engine and blueprint loaded in run_analysis (Stage 0)
        self.blueprint = None
        self.company_dna = None
        self.scoring_engine = None
        
        logger.info(
            "talent_orchestrator_initialized",
            customer_id=customer_id,
            user_id=user_id,
            pdl_query_limit=self.pdl_query_limit,
            blueprint_id=blueprint_id,
            company_dna_id=company_dna_id
        )
    
    def _emit_event(self, analysis_id: str, event_type: str, message: str, metadata: Optional[Dict[str, Any]] = None):
        """Emit an event via the callback if provided."""
        if self.event_callback:
            try:
                self.event_callback(analysis_id, event_type, message, metadata)
            except Exception as e:
                logger.warning(
                    "event_callback_failed",
                    analysis_id=analysis_id,
                    event_type=event_type,
                    error=str(e)
                )
        try:
            self.langfuse_service.trace_event(
                name=f"agentmesh.talent.{event_type}",
                input_data={"analysis_id": analysis_id, "message": message},
                output_data={"metadata": metadata or {}},
                metadata={
                    "component": "agentmesh",
                    "flow": "talent_orchestrator",
                    "analysis_id": analysis_id,
                    "event_type": event_type,
                    "customer_id": self.customer_id,
                    "user_id": self.user_id,
                },
            )
        except Exception:
            pass
    
    @staticmethod
    def _extract_role_from_jd(job_description: str) -> str:
        """
        Extract a role hint from the job description text.
        
        Uses lightweight heuristics (no LLM call) to get an initial role hint
        for stages that run before the diagnostic agent. The diagnostic agent
        will later produce the authoritative role_type from the full JD.
        """
        if not job_description or not job_description.strip():
            return ""
        
        lines = job_description.strip().split("\n")
        
        # Strategy 1: First non-empty line is often the job title
        for line in lines:
            cleaned = line.strip().strip("#").strip("*").strip()
            if cleaned and len(cleaned) < 120:
                # Skip lines that look like company names, locations, or boilerplate
                lower = cleaned.lower()
                skip_prefixes = ("about ", "company", "location", "department", "team", "posted", "apply", "http")
                if not any(lower.startswith(p) for p in skip_prefixes):
                    return cleaned
        
        return ""

    async def run_analysis(
        self,
        request: TalentAnalysisRequest
    ) -> TalentAnalysisResult:
        """
        Run complete talent intelligence analysis.
        
        Args:
            request: Analysis request with job description, ideal candidate, and resumes
            
        Returns:
            TalentAnalysisResult with all scores, reports, and provenance
        """
        # Use the analysis_id provided by the API (already created in database)
        analysis_id = request.analysis_id
        self._current_analysis_id = analysis_id  # Store for use in error callbacks
        start_time = datetime.now(timezone.utc)
        
        # Derive the initial role from the job description if not explicitly provided.
        # This is a lightweight hint for pre-diagnostic stages (e.g., baseline building).
        # The diagnostic agent (Stage 2) will produce the authoritative role_type.
        initial_role = request.role or self._extract_role_from_jd(request.job_description)
        
        logger.info(
            "role_derivation",
            analysis_id=analysis_id,
            role_from_request=request.role or "(not provided)",
            initial_role_used=initial_role,
            source="request" if request.role else "job_description"
        )
        
        # Use blueprint/DNA from request if provided, otherwise use orchestrator's
        blueprint_id = request.selected_blueprint_id or self.blueprint_id
        company_dna_id = request.company_dna_id or self.company_dna_id
        
        # Override PDL query limit if provided in request
        if request.market_search_limit:
            self.pdl_query_limit = request.market_search_limit
            logger.info(
                "pdl_query_limit_override",
                analysis_id=analysis_id,
                limit=request.market_search_limit
            )
        
        logger.info(
            "talent_analysis_start",
            analysis_id=analysis_id,
            customer_id=self.customer_id,
            user_id=self.user_id,
            role=initial_role,
            applicant_count=len(request.applicant_resume_files),
            blueprint_id=blueprint_id,
            company_dna_id=company_dna_id
        )
        trace_handle = self.langfuse_service.begin_trace_scope(
            name="agentmesh.talent.orchestrator.run_analysis",
            input_data={
                "analysis_id": analysis_id,
                "initial_role": initial_role,
                "applicant_count": len(request.applicant_resume_files),
                "historical_count": len(request.historical_candidate_files),
                "blueprint_id": blueprint_id,
                "company_dna_id": company_dna_id,
            },
            metadata={
                "component": "agentmesh",
                "flow": "talent_orchestrator",
                "analysis_id": analysis_id,
                "customer_id": self.customer_id,
                "user_id": self.user_id,
            },
            trace_id=self.langfuse_service.current_trace_id,
            session_id=analysis_id,
            user_id=str(self.user_id),
        )
        
        provenance_chains: List[ProvenanceChain] = []
        
        try:
            # ================================================================
            # STAGE 0: Load Blueprint and Company DNA (if provided)
            # ================================================================
            logger.info(
                "scoring_config_check",
                analysis_id=analysis_id,
                blueprint_id=blueprint_id,
                company_dna_id=company_dna_id
            )
            
            # Always use DynamicScoringEngine - it handles missing blueprint/DNA gracefully
            with self.langfuse_service.span_scope(
                name="agentmesh.talent.orchestrator.stage_0_load_scoring_config",
                input_data={
                    "analysis_id": analysis_id,
                    "blueprint_id": blueprint_id,
                    "company_dna_id": company_dna_id,
                },
                metadata={
                    "component": "agentmesh",
                    "flow": "talent_orchestrator",
                    "analysis_id": analysis_id,
                    "stage": "load_scoring_config",
                    "customer_id": self.customer_id,
                    "user_id": self.user_id,
                },
            ) as span_info:
                await self._load_scoring_config(blueprint_id, company_dna_id)
                observation = span_info.get("observation")
                if observation is not None:
                    try:
                        observation.update(
                            output={
                                "has_blueprint": self.blueprint is not None,
                                "has_company_dna": self.company_dna is not None,
                                "using_enhanced_pdl_builder": hasattr(self, "enhanced_pdl_builder") and self.enhanced_pdl_builder is not None,
                            }
                        )
                    except Exception:
                        pass
            # ================================================================
            # STAGE 1: Build Baseline Profile from Neo4j
            # ================================================================
            blueprint_name = self.blueprint.name if self.blueprint else "(none)"
            has_ideal = bool(request.ideal_candidate_description and request.ideal_candidate_description.strip())
            self._emit_event(
                analysis_id,
                "stage_1_started",
                f"Building baseline from Career Blueprint ({blueprint_name}) + ideal candidate preferences",
                {"stage": "baseline_build", "blueprint": blueprint_name, "has_ideal_candidate": has_ideal}
            )
            
            logger.info("stage_1_baseline_start", analysis_id=analysis_id, has_ideal_candidate=has_ideal)
            stage1_start = datetime.now(timezone.utc)
            
            with self.langfuse_service.span_scope(
                name="agentmesh.talent.orchestrator.stage_1_build_baseline",
                input_data={
                    "analysis_id": analysis_id,
                    "role": initial_role,
                    "blueprint_id": self.blueprint.id if self.blueprint else None,
                    "blueprint_name": blueprint_name,
                    "source_profile_count": self.blueprint.source_profile_count if self.blueprint else 0,
                    "has_ideal_candidate": has_ideal,
                },
                metadata={
                    "component": "agentmesh",
                    "flow": "talent_orchestrator",
                    "analysis_id": analysis_id,
                    "stage": "baseline_build",
                    "customer_id": self.customer_id,
                    "user_id": self.user_id,
                },
            ) as span_info:
                baseline_profile = self._build_baseline_from_blueprint(
                    initial_role,
                    request.ideal_candidate_description
                )
                source_profile_count = len(baseline_profile.prototype_employee_ids)
                observation = span_info.get("observation")
                if observation is not None:
                    try:
                        observation.update(
                            output={
                                "source_profile_count": source_profile_count,
                                "data_quality_score": baseline_profile.data_quality_score,
                                "average_years_experience": baseline_profile.average_years_experience,
                                "skill_distribution_count": len(baseline_profile.skill_distributions),
                            }
                        )
                    except Exception:
                        pass
            
            provenance_chains.append(WorkflowProvenanceStep(
                step_name="build_baseline",
                step_description=f"Built baseline from Career Blueprint ({source_profile_count} LinkedIn profiles) + ideal candidate preferences",
                inputs={
                    "blueprint_id": self.blueprint.id if self.blueprint else None,
                    "has_ideal_candidate": has_ideal,
                },
                outputs={"source_profile_count": source_profile_count},
                service_used="CareerBlueprint + IdealCandidate",
                timestamp=stage1_start,
                duration_seconds=(datetime.now(timezone.utc) - stage1_start).total_seconds()
            ))
            
            self._emit_event(
                analysis_id,
                "stage_1_completed",
                f"Baseline profile built from {source_profile_count} LinkedIn profiles",
                {"stage": "baseline_build", "source_profile_count": source_profile_count}
            )
            
            logger.info(
                "stage_1_baseline_complete",
                analysis_id=analysis_id,
                source_profile_count=source_profile_count
            )
            
            # ================================================================
            # STAGE 2: Run Diagnostic Agent
            # ================================================================
            self._emit_event(
                analysis_id,
                "stage_2_started",
                "Analyzing job requirements with AI (Diagnostic Agent)",
                {"stage": "diagnostic_analysis", "agent": "gpt-4o-mini"}
            )
            
            logger.info("stage_2_diagnostic_start", analysis_id=analysis_id)
            stage2_start = datetime.now(timezone.utc)
            
            with self.langfuse_service.span_scope(
                name="agentmesh.talent.orchestrator.stage_2_diagnostic_analysis",
                input_data={
                    "analysis_id": analysis_id,
                    "initial_role": initial_role,
                    "job_description": request.job_description[:4000],
                    "ideal_candidate_description": request.ideal_candidate_description[:4000],
                },
                metadata={
                    "component": "agentmesh",
                    "flow": "talent_orchestrator",
                    "analysis_id": analysis_id,
                    "stage": "diagnostic_analysis",
                    "customer_id": self.customer_id,
                    "user_id": self.user_id,
                },
            ) as span_info:
                diagnostic_report = await self._run_diagnostic(
                    request.job_description,
                    request.ideal_candidate_description,
                    baseline_profile,
                    initial_role
                )
                observation = span_info.get("observation")
                if observation is not None:
                    try:
                        observation.update(
                            output={
                                "confidence": diagnostic_report.confidence,
                                "role_type": diagnostic_report.role_type,
                                "attribute_count": len(diagnostic_report.attribute_weights),
                                "required_skill_count": len(diagnostic_report.required_skills),
                                "preferred_skill_count": len(diagnostic_report.preferred_skills),
                            }
                        )
                    except Exception:
                        pass
            
            # After the diagnostic, the authoritative role comes from the JD analysis.
            # All subsequent stages use this instead of the initial hint.
            role = diagnostic_report.role_type
            
            logger.info(
                "role_resolved_from_diagnostic",
                analysis_id=analysis_id,
                initial_role=initial_role,
                diagnostic_role=role,
            )
            
            provenance_chains.append(WorkflowProvenanceStep(
                step_name="diagnostic_analysis",
                step_description="Analyzed job requirements and prioritized attributes",
                inputs={
                    "job_description": request.job_description[:200],
                    "ideal_candidate": request.ideal_candidate_description[:200]
                },
                outputs={
                    "attribute_count": len(diagnostic_report.attribute_weights),
                    "confidence": diagnostic_report.confidence
                },
                service_used="DiagnosticAgentService",
                llm_provider="openai",
                llm_model="gpt-4o-mini",
                timestamp=stage2_start,
                duration_seconds=(datetime.now(timezone.utc) - stage2_start).total_seconds()
            ))
            
            self._emit_event(
                analysis_id,
                "stage_2_completed",
                f"Requirements analyzed ({len(diagnostic_report.attribute_weights)} key attributes identified)",
                {"stage": "diagnostic_analysis", "confidence": diagnostic_report.confidence}
            )
            
            logger.info(
                "stage_2_diagnostic_complete",
                analysis_id=analysis_id,
                attribute_count=len(diagnostic_report.attribute_weights),
                confidence=diagnostic_report.confidence
            )
            
            # ================================================================
            # STAGE 3: Parse Applicant Resumes
            # ================================================================
            self._emit_event(
                analysis_id,
                "stage_3_started",
                f"Parsing {len(request.applicant_resume_files[:50])} applicant resumes with {self.resume_parser.model}",
                {"stage": "parse_resumes", "resume_count": len(request.applicant_resume_files[:50])}
            )
            
            logger.info("stage_3_parse_resumes_start", analysis_id=analysis_id)
            stage3_start = datetime.now(timezone.utc)
            
            with self.langfuse_service.span_scope(
                name="agentmesh.talent.orchestrator.stage_3_parse_resumes",
                input_data={
                    "analysis_id": analysis_id,
                    "requested_resume_count": len(request.applicant_resume_files[:50]),
                },
                metadata={
                    "component": "agentmesh",
                    "flow": "talent_orchestrator",
                    "analysis_id": analysis_id,
                    "stage": "parse_resumes",
                    "customer_id": self.customer_id,
                    "user_id": self.user_id,
                },
            ) as span_info:
                parsed_resumes = await self._parse_resumes(
                    request.applicant_resume_files[:50],  # Limit to 50
                    customer_id=self.customer_id,
                    analysis_id=analysis_id
                )
                observation = span_info.get("observation")
                if observation is not None:
                    try:
                        observation.update(
                            output={
                                "parsed_count": len(parsed_resumes),
                                "requested_count": len(request.applicant_resume_files[:50]),
                            }
                        )
                    except Exception:
                        pass
            
            provenance_chains.append(WorkflowProvenanceStep(
                step_name="parse_resumes",
                step_description=f"Parsed {len(parsed_resumes)} applicant resumes using text+LLM ({self.resume_parser.model})",
                inputs={"resume_count": len(request.applicant_resume_files[:50])},
                outputs={"parsed_count": len(parsed_resumes)},
                service_used="TextLLMParser",
                llm_provider="openai",
                llm_model=self.resume_parser.model,
                timestamp=stage3_start,
                duration_seconds=(datetime.now(timezone.utc) - stage3_start).total_seconds()
            ))
            
            self._emit_event(
                analysis_id,
                "stage_3_completed",
                f"Successfully parsed {len(parsed_resumes)} resumes",
                {"stage": "parse_resumes", "parsed_count": len(parsed_resumes)}
            )
            
            logger.info(
                "stage_3_parse_resumes_complete",
                analysis_id=analysis_id,
                parsed_count=len(parsed_resumes)
            )
            
            # ================================================================
            # STAGE 3B: Parse Historical Candidate Resumes (if any)
            # Historical candidates are parsed separately but scored together
            # with applicants - the only difference is the source label
            # ================================================================
            parsed_historical = []
            if request.historical_candidate_files:
                historical_count = len(request.historical_candidate_files[:50])
                self._emit_event(
                    analysis_id,
                    "stage_3b_started",
                    f"Parsing {historical_count} previous candidate resumes",
                    {"stage": "parse_historical", "resume_count": historical_count}
                )
                
                logger.info("stage_3b_parse_historical_start", analysis_id=analysis_id)
                stage3b_start = datetime.now(timezone.utc)
                
                with self.langfuse_service.span_scope(
                    name="agentmesh.talent.orchestrator.stage_3b_parse_historical_resumes",
                    input_data={
                        "analysis_id": analysis_id,
                        "requested_resume_count": historical_count,
                    },
                    metadata={
                        "component": "agentmesh",
                        "flow": "talent_orchestrator",
                        "analysis_id": analysis_id,
                        "stage": "parse_historical_resumes",
                        "customer_id": self.customer_id,
                        "user_id": self.user_id,
                    },
                ) as span_info:
                    parsed_historical = await self._parse_resumes(
                        request.historical_candidate_files[:50],  # Limit to 50
                        customer_id=self.customer_id,
                        analysis_id=analysis_id
                    )
                    observation = span_info.get("observation")
                    if observation is not None:
                        try:
                            observation.update(
                                output={
                                    "parsed_count": len(parsed_historical),
                                    "requested_count": historical_count,
                                }
                            )
                        except Exception:
                            pass
                
                # Mark each parsed resume as historical for source tracking
                for resume in parsed_historical:
                    resume.is_historical = True
                
                provenance_chains.append(WorkflowProvenanceStep(
                    step_name="parse_historical_resumes",
                    step_description=f"Parsed {len(parsed_historical)} previous candidate resumes using text+LLM ({self.resume_parser.model})",
                    inputs={"resume_count": historical_count},
                    outputs={"parsed_count": len(parsed_historical)},
                    service_used="TextLLMParser",
                    llm_provider="openai",
                    llm_model=self.resume_parser.model,
                    timestamp=stage3b_start,
                    duration_seconds=(datetime.now(timezone.utc) - stage3b_start).total_seconds()
                ))
                
                self._emit_event(
                    analysis_id,
                    "stage_3b_completed",
                    f"Successfully parsed {len(parsed_historical)} previous candidate resumes",
                    {"stage": "parse_historical", "parsed_count": len(parsed_historical)}
                )
                
                logger.info(
                    "stage_3b_parse_historical_complete",
                    analysis_id=analysis_id,
                    parsed_count=len(parsed_historical)
                )
            
            # ================================================================
            # STAGE 4: Score All Internal Candidates (Applicants + Previous)
            # The scoring is identical - only the source label differs
            # ================================================================
            total_internal = len(parsed_resumes) + len(parsed_historical)
            self._emit_event(
                analysis_id,
                "stage_4_started",
                f"Scoring {total_internal} internal candidates ({len(parsed_resumes)} applicants, {len(parsed_historical)} previous)",
                {"stage": "score_internal", "applicant_count": len(parsed_resumes), "previous_count": len(parsed_historical)}
            )
            
            logger.info("stage_4_score_internal_start", analysis_id=analysis_id, total=total_internal)
            stage4_start = datetime.now(timezone.utc)
            
            with self.langfuse_service.span_scope(
                name="agentmesh.talent.orchestrator.stage_4_score_internal_candidates",
                input_data={
                    "analysis_id": analysis_id,
                    "applicant_count": len(parsed_resumes),
                    "historical_count": len(parsed_historical),
                },
                metadata={
                    "component": "agentmesh",
                    "flow": "talent_orchestrator",
                    "analysis_id": analysis_id,
                    "stage": "score_internal",
                    "customer_id": self.customer_id,
                    "user_id": self.user_id,
                },
            ) as span_info:
                # Score current applicants
                applicant_scores = await self._score_candidates(
                    parsed_resumes,
                    diagnostic_report,
                    baseline_profile,
                    CandidateSource.APPLICANT
                )
                
                # Score previous candidates (same scoring, different source label)
                previous_candidate_scores = []
                if parsed_historical:
                    previous_candidate_scores = await self._score_candidates(
                        parsed_historical,
                        diagnostic_report,
                        baseline_profile,
                        CandidateSource.PREVIOUS_CANDIDATE
                    )
                observation = span_info.get("observation")
                if observation is not None:
                    try:
                        observation.update(
                            output={
                                "applicant_scored": len(applicant_scores),
                                "previous_scored": len(previous_candidate_scores),
                            }
                        )
                    except Exception:
                        pass
            
            # Combined provenance for all internal candidate scoring
            all_internal_scores = applicant_scores + previous_candidate_scores
            provenance_chains.append(WorkflowProvenanceStep(
                step_name="score_internal_candidates",
                step_description=f"Scored {len(all_internal_scores)} internal candidates ({len(applicant_scores)} applicants, {len(previous_candidate_scores)} previous) across 5 dimensions",
                inputs={"applicant_count": len(parsed_resumes), "previous_count": len(parsed_historical)},
                outputs={
                    "applicant_scored": len(applicant_scores),
                    "previous_scored": len(previous_candidate_scores),
                    "top_score": max([s.overall_score for s in all_internal_scores]) if all_internal_scores else 0
                },
                service_used="DynamicScoringEngine",
                timestamp=stage4_start,
                duration_seconds=(datetime.now(timezone.utc) - stage4_start).total_seconds()
            ))
            
            self._emit_event(
                analysis_id,
                "stage_4_completed",
                f"Internal candidate scoring complete ({len(applicant_scores)} applicants, {len(previous_candidate_scores)} previous)",
                {"stage": "score_internal", "applicant_scored": len(applicant_scores), "previous_scored": len(previous_candidate_scores)}
            )
            
            logger.info(
                "stage_4_score_internal_complete",
                analysis_id=analysis_id,
                applicant_scored=len(applicant_scores),
                previous_scored=len(previous_candidate_scores)
            )
            
            # ================================================================
            # STAGE 5: Build PDL Query & Search Market
            # ================================================================
            self._emit_event(
                analysis_id,
                "stage_5_started",
                "Searching PDL for ideal candidates in the market",
                {"stage": "market_search", "limit": self.pdl_query_limit}
            )
            
            logger.info("stage_5_market_search_start", analysis_id=analysis_id)
            stage5_start = datetime.now(timezone.utc)
            
            with self.langfuse_service.span_scope(
                name="agentmesh.talent.orchestrator.stage_5_market_search",
                input_data={
                    "analysis_id": analysis_id,
                    "role": role,
                    "pdl_limit": self.pdl_query_limit,
                    "applicant_score_count": len(applicant_scores),
                },
                metadata={
                    "component": "agentmesh",
                    "flow": "talent_orchestrator",
                    "analysis_id": analysis_id,
                    "stage": "market_search",
                    "customer_id": self.customer_id,
                    "user_id": self.user_id,
                },
            ) as span_info:
                pdl_query, market_candidates = await self._search_market(
                    diagnostic_report,
                    baseline_profile,
                    applicant_scores,
                    role
                )
                observation = span_info.get("observation")
                if observation is not None:
                    try:
                        observation.update(
                            output={
                                "query_version": getattr(pdl_query, "version", None),
                                "required_skill_count": len(getattr(pdl_query, "required_skills", []) or []),
                                "candidate_count": len(market_candidates),
                            }
                        )
                    except Exception:
                        pass
            
            provenance_chains.append(WorkflowProvenanceStep(
                step_name="build_pdl_query",
                step_description="Built PDL query from diagnostic and baseline",
                inputs={"role": role},
                outputs={
                    "query_version": pdl_query.version,
                    "required_skills": len(pdl_query.required_skills)
                },
                service_used="PDLQueryBuilder",
                timestamp=stage5_start,
                duration_seconds=0.1  # Fast, deterministic
            ))
            
            provenance_chains.append(WorkflowProvenanceStep(
                step_name="search_market",
                step_description=f"Searched PDL for market candidates, found {len(market_candidates)}",
                inputs={"query_version": pdl_query.version, "limit": pdl_query.limit},
                outputs={"candidate_count": len(market_candidates)},
                service_used="PDL API",
                timestamp=stage5_start,
                duration_seconds=(datetime.now(timezone.utc) - stage5_start).total_seconds()
            ))
            
            self._emit_event(
                analysis_id,
                "stage_5_completed",
                f"Market search complete ({len(market_candidates)} candidates found)",
                {"stage": "market_search", "candidate_count": len(market_candidates)}
            )
            
            logger.info(
                "stage_5_market_search_complete",
                analysis_id=analysis_id,
                market_candidate_count=len(market_candidates)
            )
            
            # ================================================================
            # STAGE 6: Score Market Candidates
            # ================================================================
            self._emit_event(
                analysis_id,
                "stage_6_started",
                f"Scoring {len(market_candidates)} market candidates across 6 dimensions",
                {"stage": "score_market", "candidate_count": len(market_candidates)}
            )
            
            logger.info("stage_6_score_market_start", analysis_id=analysis_id)
            stage6_start = datetime.now(timezone.utc)
            
            with self.langfuse_service.span_scope(
                name="agentmesh.talent.orchestrator.stage_6_score_market_candidates",
                input_data={
                    "analysis_id": analysis_id,
                    "market_candidate_count": len(market_candidates),
                },
                metadata={
                    "component": "agentmesh",
                    "flow": "talent_orchestrator",
                    "analysis_id": analysis_id,
                    "stage": "score_market",
                    "customer_id": self.customer_id,
                    "user_id": self.user_id,
                },
            ) as span_info:
                market_scores = await self._score_candidates(
                    market_candidates,
                    diagnostic_report,
                    baseline_profile,
                    CandidateSource.MARKET
                )
                observation = span_info.get("observation")
                if observation is not None:
                    try:
                        observation.update(
                            output={
                                "market_candidate_count": len(market_candidates),
                                "market_scored_count": len(market_scores),
                            }
                        )
                    except Exception:
                        pass
            
            provenance_chains.append(WorkflowProvenanceStep(
                step_name="score_market",
                step_description=f"Scored {len(market_scores)} market candidates across 5 dimensions",
                inputs={"candidate_count": len(market_candidates)},
                outputs={
                    "scored_count": len(market_scores),
                    "top_score": max([s.overall_score for s in market_scores]) if market_scores else 0
                },
                service_used="DynamicScoringEngine",
                timestamp=stage6_start,
                duration_seconds=(datetime.now(timezone.utc) - stage6_start).total_seconds()
            ))
            
            self._emit_event(
                analysis_id,
                "stage_6_completed",
                f"Market candidate scoring complete ({len(market_scores)} scored)",
                {"stage": "score_market", "scored_count": len(market_scores)}
            )
            
            logger.info(
                "stage_6_score_market_complete",
                analysis_id=analysis_id,
                scored_count=len(market_scores)
            )
            
            # ================================================================
            # STAGE 7: Select Top Overall Candidates & Run Synthesis
            # ================================================================
            self._emit_event(
                analysis_id,
                "stage_7_started",
                "Running AI synthesis to generate insights (Synthesis Agent)",
                {"stage": "synthesis", "agent": "gpt-4o-mini"}
            )
            
            logger.info("stage_7_synthesis_start", analysis_id=analysis_id)
            stage7_start = datetime.now(timezone.utc)
            
            with self.langfuse_service.span_scope(
                name="agentmesh.talent.orchestrator.stage_7_synthesis",
                input_data={
                    "analysis_id": analysis_id,
                    "applicant_count": len(applicant_scores),
                    "previous_count": len(previous_candidate_scores),
                    "market_count": len(market_scores),
                },
                metadata={
                    "component": "agentmesh",
                    "flow": "talent_orchestrator",
                    "analysis_id": analysis_id,
                    "stage": "synthesis",
                    "customer_id": self.customer_id,
                    "user_id": self.user_id,
                },
            ) as span_info:
                # Combine and sort all candidates by overall_score
                all_candidates = applicant_scores + previous_candidate_scores + market_scores
                all_candidates.sort(key=lambda c: c.overall_score, reverse=True)
                top_overall = all_candidates[:3]  # Top 3 overall
                
                logger.info(
                    "top_candidates_selected",
                    analysis_id=analysis_id,
                    top_count=len(top_overall),
                    top_scores=[c.overall_score for c in top_overall]
                )
                
                # Run synthesis agent
                synthesis_report = await self._run_synthesis(
                    diagnostic_report,
                    applicant_scores,
                    market_scores,
                    top_overall_count=3
                )
                observation = span_info.get("observation")
                if observation is not None:
                    try:
                        observation.update(
                            output={
                                "top_overall_count": len(top_overall),
                                "insight_count": len(synthesis_report.key_insights),
                                "pattern_count": len(synthesis_report.pattern_highlights),
                                "recommendation_count": len(synthesis_report.recommendations),
                            }
                        )
                    except Exception:
                        pass
            
            provenance_chains.append(WorkflowProvenanceStep(
                step_name="synthesis_report",
                step_description="Synthesized analysis into comprehensive report",
                inputs={
                    "applicant_count": len(applicant_scores),
                    "market_count": len(market_scores),
                    "top_overall_count": len(top_overall)
                },
                outputs={
                    "pattern_count": len(synthesis_report.pattern_highlights),
                    "insight_count": len(synthesis_report.key_insights),
                    "recommendation_count": len(synthesis_report.recommendations)
                },
                service_used="SynthesisAgentService",
                llm_provider="openai",
                llm_model="gpt-4o-mini",
                timestamp=stage7_start,
                duration_seconds=(datetime.now(timezone.utc) - stage7_start).total_seconds()
            ))
            
            self._emit_event(
                analysis_id,
                "stage_7_completed",
                f"Synthesis complete ({len(synthesis_report.key_insights)} insights, {len(top_overall)} top candidates)",
                {"stage": "synthesis", "insight_count": len(synthesis_report.key_insights), "top_count": len(top_overall)}
            )
            
            logger.info(
                "stage_7_synthesis_complete",
                analysis_id=analysis_id,
                top_candidate_count=len(top_overall),
                pattern_count=len(synthesis_report.pattern_highlights)
            )
            
            # ================================================================
            # STAGE 8: Build Final Result
            # ================================================================
            total_duration = (datetime.now(timezone.utc) - start_time).total_seconds()
            
            with self.langfuse_service.span_scope(
                name="agentmesh.talent.orchestrator.stage_8_build_result",
                input_data={
                    "analysis_id": analysis_id,
                    "duration_seconds": total_duration,
                },
                metadata={
                    "component": "agentmesh",
                    "flow": "talent_orchestrator",
                    "analysis_id": analysis_id,
                    "stage": "build_result",
                    "customer_id": self.customer_id,
                    "user_id": self.user_id,
                },
            ) as span_info:
                # Convert PDLQueryParams to PDLQuery for the result
                api_payload = self.pdl_query_builder.convert_to_pdl_api_payload(pdl_query)
                
                pdl_query_result = PDLQuery(
                    base_query=str(api_payload.get("query", "")),  # PDL API uses "query" not "search_query"
                    params=api_payload,
                    version=1,
                    refinement_reason="Initial query based on diagnostic analysis"
                )
                
                result = TalentAnalysisResult(
                    analysis_id=analysis_id,
                    status=AnalysisStatus.COMPLETED,
                    
                    # Inputs
                    job_description=request.job_description,
                    ideal_candidate_description=request.ideal_candidate_description,
                    
                    # Core analysis outputs
                    diagnostic_report=diagnostic_report,
                    baseline_profile=baseline_profile,
                    synthesis=synthesis_report,
                    
                    # Candidate results
                    applicant_results=applicant_scores,
                    market_results=market_scores,
                    top_overall=top_overall,
                    
                    # Patterns from synthesis
                    patterns=synthesis_report.pattern_highlights,
                    
                    # Provenance
                    provenance=provenance_chains,
                    
                    # Metadata
                    overall_confidence=0.85,  # Default confidence; could be extracted from synthesis if needed
                    created_at=start_time,
                    completed_at=datetime.now(timezone.utc),
                    pdl_query=pdl_query_result
                )
                observation = span_info.get("observation")
                if observation is not None:
                    try:
                        observation.update(
                            output={
                                "status": AnalysisStatus.COMPLETED.value,
                                "applicant_count": len(applicant_scores),
                                "market_count": len(market_scores),
                                "top_overall_count": len(top_overall),
                                "duration_seconds": total_duration,
                            }
                        )
                    except Exception:
                        pass
            
            logger.info(
                "talent_analysis_complete",
                analysis_id=analysis_id,
                duration_seconds=total_duration,
                applicant_count=len(applicant_scores),
                market_count=len(market_scores),
                top_candidates=len(top_overall)
            )
            self.langfuse_service.end_trace_scope(
                trace_handle,
                output_data={
                    "status": AnalysisStatus.COMPLETED.value,
                    "applicant_count": len(applicant_scores),
                    "market_count": len(market_scores),
                    "top_candidates": len(top_overall),
                    "duration_seconds": total_duration,
                },
                metadata={"analysis_id": analysis_id},
            )
            trace_handle = None
            
            return result
            
        except Exception as e:
            self.langfuse_service.end_trace_scope(
                trace_handle,
                metadata={"analysis_id": analysis_id},
                error=e,
            )
            trace_handle = None
            # Emit error event
            self._emit_event(
                analysis_id,
                "analysis_error",
                f"Analysis failed: {str(e)}",
                {"error": str(e), "error_type": type(e).__name__}
            )
            
            logger.error(
                "talent_analysis_failed",
                analysis_id=analysis_id,
                customer_id=self.customer_id,
                user_id=self.user_id,
                error=str(e),
                exc_info=True
            )
            
            # Re-raise the exception to be handled by the API layer
            raise
        finally:
            if trace_handle is not None:
                self.langfuse_service.end_trace_scope(
                    trace_handle,
                    metadata={"analysis_id": analysis_id, "status": "finalized_without_explicit_end"},
                )
    
    # ========================================================================
    # PRIVATE STAGE METHODS
    # ========================================================================
    
    @staticmethod
    def _parse_ideal_candidate(ideal_candidate_description: str) -> Dict[str, Any]:
        """
        Parse the ideal candidate description into structured components.
        
        The frontend sends this as JSON with structured fields:
        - mustHaves: required skills/experience
        - niceToHaves: preferred skills/experience
        - dealbreakers: disqualifying criteria
        - personalityTraits: cultural/soft skill requirements
        - hiringManagerNotes: free-form hiring manager context
        
        Falls back to treating the whole string as free-form notes.
        """
        import json as _json
        
        if not ideal_candidate_description or not ideal_candidate_description.strip():
            return {}
        
        try:
            parsed = _json.loads(ideal_candidate_description)
            if isinstance(parsed, dict):
                return parsed
        except (_json.JSONDecodeError, TypeError):
            pass
        
        return {"hiringManagerNotes": ideal_candidate_description.strip()}

    def _build_baseline_from_blueprint(
        self,
        role: str,
        ideal_candidate_description: str = ""
    ) -> BaselineProfile:
        """
        Stage 1: Build baseline profile from the Career Blueprint + ideal candidate input.
        
        Two sources are merged:
        1. Career Blueprint — patterns from enriched LinkedIn profiles (skills, companies,
           experience, career paths)
        2. Ideal Candidate Description — the user's stated must-haves, nice-to-haves,
           dealbreakers, and hiring manager notes
        
        If no blueprint is loaded, the baseline is built solely from the ideal candidate
        input. The diagnostic agent can still function with this.
        """
        # Parse the ideal candidate input
        ideal = self._parse_ideal_candidate(ideal_candidate_description)
        
        has_blueprint = self.blueprint is not None
        has_ideal = bool(ideal)
        
        if not has_blueprint and not has_ideal:
            logger.info("baseline_no_inputs", role=role)
            return BaselineProfile(
                role_type=role,
                prototype_employee_ids=[],
                attribute_weights={},
                common_career_paths=[],
                skill_distributions={},
                company_clusters=[],
                average_years_experience=5.0,
                success_patterns=[],
                data_quality_score=0.0
            )
        
        # ---- Blueprint data (if available) ----
        bp = self.blueprint
        skill_profile = (bp.skill_profile or {}) if bp else {}
        company_progression = (bp.company_progression or {}) if bp else {}
        experience_profile = (bp.experience_profile or {}) if bp else {}
        role_progression = (bp.role_progression or {}) if bp else {}
        
        # Skill distributions from Blueprint
        skill_distributions: Dict[str, float] = {}
        for skill in skill_profile.get("core_skills", []):
            skill_distributions[skill] = 1.0
        skill_freqs = skill_profile.get("skill_frequencies", {})
        for skill, freq in skill_freqs.items():
            if skill not in skill_distributions:
                skill_distributions[skill] = freq if isinstance(freq, (int, float)) else 0.5
        
        # Company clusters from Blueprint
        company_clusters = company_progression.get("common_companies", [])
        
        # Average experience from Blueprint
        avg_years = experience_profile.get("avg_years", 5.0)
        
        # Career paths from role progression
        common_titles = role_progression.get("common_titles", [])
        career_paths = []
        if common_titles:
            from src.models.talent_analysis import CareerPathPattern
            career_paths.append(CareerPathPattern(
                path_description=" → ".join(common_titles[:5]),
                frequency=(bp.source_profile_count or 1) if bp else 1,
                example_employees=(bp.source_pdl_person_ids or []) if bp else []
            ))
        
        # ---- Ideal candidate data (user input) ----
        # Must-haves get highest weight; nice-to-haves are supplementary
        must_haves = ideal.get("mustHaves", "")
        nice_to_haves = ideal.get("niceToHaves", "")
        dealbreakers = ideal.get("dealbreakers", "")
        personality_traits = ideal.get("personalityTraits", "")
        hiring_notes = ideal.get("hiringManagerNotes", "")
        
        # Extract skill-like tokens from must-haves and nice-to-haves
        # These are user-stated requirements, so they get high weight
        for text, weight in [(must_haves, 1.0), (nice_to_haves, 0.6)]:
            if text:
                tokens = [t.strip().lower() for t in text.replace("\n", ",").split(",") if t.strip()]
                for token in tokens:
                    if token and len(token) < 80:
                        if token not in skill_distributions:
                            skill_distributions[token] = weight
                        else:
                            skill_distributions[token] = max(skill_distributions[token], weight)
        
        # ---- Build success patterns from both sources ----
        success_patterns = []
        if must_haves:
            success_patterns.append(f"Must-haves: {must_haves[:200]}")
        if nice_to_haves:
            success_patterns.append(f"Nice-to-haves: {nice_to_haves[:200]}")
        if dealbreakers:
            success_patterns.append(f"Dealbreakers: {dealbreakers[:200]}")
        if personality_traits:
            success_patterns.append(f"Traits: {personality_traits[:200]}")
        if hiring_notes:
            success_patterns.append(f"Hiring notes: {hiring_notes[:200]}")
        if skill_profile.get("core_skills"):
            success_patterns.append(f"Blueprint core skills: {', '.join(skill_profile['core_skills'][:5])}")
        if company_clusters:
            success_patterns.append(f"Blueprint companies: {', '.join(company_clusters[:5])}")
        if common_titles:
            success_patterns.append(f"Blueprint titles: {', '.join(common_titles[:5])}")
        
        # Scoring weights from Blueprint (or defaults)
        attribute_weights = {}
        if bp and bp.scoring_weights:
            attribute_weights = bp.scoring_weights
        if not attribute_weights:
            attribute_weights = {
                "technical_skills": 0.30,
                "experience": 0.25,
                "trajectory": 0.20,
                "company_background": 0.15,
                "education": 0.10
            }
        
        # Data quality: blueprint profiles + ideal candidate completeness
        profile_count = (bp.source_profile_count or 0) if bp else 0
        ideal_completeness = sum(1 for v in [must_haves, nice_to_haves, personality_traits, hiring_notes] if v) / 4.0
        data_quality = min(1.0, (profile_count / 5.0) * 0.7 + ideal_completeness * 0.3)
        
        baseline = BaselineProfile(
            role_type=role or (bp.role_category if bp else "") or "",
            prototype_employee_ids=(bp.source_pdl_person_ids or []) if bp else [],
            attribute_weights=attribute_weights,
            common_career_paths=career_paths,
            skill_distributions=skill_distributions,
            company_clusters=company_clusters,
            average_years_experience=avg_years,
            success_patterns=success_patterns,
            data_quality_score=data_quality
        )
        
        logger.info(
            "baseline_built",
            has_blueprint=has_blueprint,
            blueprint_id=bp.id if bp else None,
            blueprint_name=bp.name if bp else None,
            source_profile_count=profile_count,
            ideal_fields_provided=sum(1 for v in ideal.values() if v),
            skill_count=len(skill_distributions),
            company_count=len(company_clusters),
            success_pattern_count=len(success_patterns),
            avg_years=avg_years,
            data_quality=data_quality
        )
        
        return baseline
    
    async def _run_diagnostic(
        self,
        job_description: str,
        ideal_candidate: str,
        baseline: BaselineProfile,
        role: str
    ) -> DiagnosticReport:
        """Stage 2: Run diagnostic agent."""
        diagnostic_agent = DiagnosticAgentService(
            customer_id=self.customer_id,
            user_id=self.user_id,
            llm_provider="openai",
            llm_model="gpt-4o-mini"
        )
        
        diagnostic_input = DiagnosticInput(
            job_description=job_description,
            ideal_candidate_description=ideal_candidate,
            baseline_profile=baseline,
            role=role
        )
        
        return await asyncio.to_thread(
            diagnostic_agent.analyze,
            diagnostic_input
        )
    
    async def _load_scoring_config(
        self,
        blueprint_id: Optional[int],
        company_dna_id: Optional[int]
    ) -> None:
        """
        Load Career Blueprint and Company DNA from database for dynamic scoring.
        
        Args:
            blueprint_id: Optional blueprint ID to load
            company_dna_id: Optional company DNA ID to load
        """
        from src.models.database import SessionLocal, init_database
        from src.models.talent_config import CareerBlueprint, CompanyDNAProfile
        
        # Ensure database is initialized
        if SessionLocal is None:
            init_database()
        
        db = SessionLocal()
        try:
            # Load blueprint if provided
            if blueprint_id:
                self.blueprint = db.query(CareerBlueprint).filter(
                    CareerBlueprint.id == blueprint_id,
                    CareerBlueprint.customer_id == self.customer_id,
                    CareerBlueprint.is_active == True
                ).first()
                
                if self.blueprint:
                    logger.info(
                        "loaded_career_blueprint",
                        blueprint_id=blueprint_id,
                        blueprint_name=self.blueprint.name
                    )
                else:
                    logger.warning(
                        "blueprint_not_found",
                        blueprint_id=blueprint_id,
                        customer_id=self.customer_id
                    )
            
            # Load company DNA if provided
            if company_dna_id:
                self.company_dna = db.query(CompanyDNAProfile).filter(
                    CompanyDNAProfile.id == company_dna_id,
                    CompanyDNAProfile.customer_id == self.customer_id,
                    CompanyDNAProfile.is_active == True
                ).first()
                
                if self.company_dna:
                    logger.info(
                        "loaded_company_dna",
                        dna_id=company_dna_id,
                        company_name=self.company_dna.company_name,
                        role_category=self.company_dna.role_category
                    )
                else:
                    logger.warning(
                        "company_dna_not_found",
                        dna_id=company_dna_id,
                        customer_id=self.customer_id
                    )
            
            # Always use DynamicScoringEngine - it handles missing blueprint/DNA gracefully
            # This ensures consistent scoring across all candidates
            self.scoring_engine = DynamicScoringEngine(
                blueprint=self.blueprint,
                company_dna=self.company_dna
            )
            
            # Use enhanced PDL query builder if we have blueprint or DNA
            if self.blueprint or self.company_dna:
                self.enhanced_pdl_builder = EnhancedPDLQueryBuilder(
                    blueprint=self.blueprint,
                    company_dna=self.company_dna
                )
            else:
                self.enhanced_pdl_builder = None
            
            logger.info(
                "using_dynamic_scoring_engine",
                has_blueprint=self.blueprint is not None,
                has_dna=self.company_dna is not None,
                blueprint_name=self.blueprint.name if self.blueprint else None,
                dna_company=self.company_dna.company_name if self.company_dna else None,
                using_enhanced_pdl_builder=self.enhanced_pdl_builder is not None
            )
                
        finally:
            db.close()
    
    async def _parse_resumes(
        self,
        resume_files: List[Any],
        customer_id: Optional[str] = None,
        analysis_id: Optional[str] = None
    ) -> List[ParsedResume]:
        """Stage 3: Parse applicant resumes with text extraction + LLM.
        
        Uses concurrent parsing (up to 10 simultaneous API calls) for speed.
        A batch of 100 resumes at ~12s each takes ~2 min instead of ~20 min.
        
        Accepts either:
        - Legacy format: List of (file_bytes, filename) tuples
        - Rich format: List of ApplicantResumeData or dicts with metadata
        
        Uses caching to skip parsing for candidates we've already processed.
        Emits progress events as resumes are parsed.
        """
        parsed = []
        cache_hits = 0
        cache_misses = 0
        failed_count = 0
        completed_count = 0
        total_resumes = len(resume_files)
        
        MAX_CONCURRENT_PARSES = 10
        semaphore = asyncio.Semaphore(MAX_CONCURRENT_PARSES)
        
        # Initialize candidate service for cache lookup
        candidate_service = None
        db = None
        if customer_id:
            try:
                from src.models import database
                from src.services.candidate_service import CandidateService
                if database.SessionLocal is None:
                    database.init_database()
                db = database.SessionLocal()
                candidate_service = CandidateService(db, customer_id)
            except Exception as e:
                logger.warning(f"Failed to initialize candidate service for cache: {e}")
        
        # Phase 1: Pre-process all resumes — extract metadata and check cache
        to_parse = []
        
        try:
            for idx, resume_data in enumerate(resume_files):
                try:
                    # Handle legacy tuple format: (file_bytes, filename)
                    if isinstance(resume_data, tuple) and len(resume_data) == 2:
                        file_bytes, filename = resume_data
                        metadata = {}
                    # Handle dict format from Greenhouse connector
                    elif isinstance(resume_data, dict):
                        file_bytes = resume_data.get("file_bytes")
                        filename = resume_data.get("filename", "resume.pdf")
                        raw_greenhouse_id = resume_data.get("greenhouse_id")
                        metadata = {
                            "greenhouse_id": raw_greenhouse_id or resume_data.get("candidate_id") or resume_data.get("metadata", {}).get("greenhouse_candidate_id"),
                            "candidate_name": resume_data.get("candidate_name"),
                            "candidate_email": resume_data.get("email") or resume_data.get("candidate_email"),
                            "linkedin_url": resume_data.get("linkedin_url"),
                            "phone": resume_data.get("phone"),
                            "location": resume_data.get("location"),
                        }
                        logger.info(
                            "resume_metadata_extracted",
                            raw_greenhouse_id=raw_greenhouse_id,
                            resolved_greenhouse_id=metadata.get("greenhouse_id"),
                            candidate_name=metadata.get("candidate_name"),
                            candidate_email=metadata.get("candidate_email"),
                            resume_data_keys=list(resume_data.keys())
                        )
                    # Handle ApplicantResumeData model
                    elif hasattr(resume_data, 'file_bytes'):
                        file_bytes = resume_data.file_bytes
                        filename = resume_data.filename
                        metadata = {
                            "greenhouse_id": getattr(resume_data, 'greenhouse_id', None),
                            "candidate_name": getattr(resume_data, 'candidate_name', None),
                            "candidate_email": getattr(resume_data, 'candidate_email', None),
                            "linkedin_url": getattr(resume_data, 'linkedin_url', None),
                            "phone": getattr(resume_data, 'phone', None),
                            "location": getattr(resume_data, 'location', None),
                        }
                    else:
                        logger.warning(f"Unknown resume data format: {type(resume_data)}")
                        failed_count += 1
                        continue
                    
                    # Check cache first
                    if candidate_service:
                        cached_data = candidate_service.get_cached_parsed_resume(
                            email=metadata.get("candidate_email"),
                            greenhouse_id=metadata.get("greenhouse_id")
                        )
                        if cached_data:
                            cache_hits += 1
                            resume = ParsedResume(
                                full_name=cached_data.get("full_name"),
                                email=cached_data.get("email"),
                                phone=cached_data.get("phone"),
                                linkedin_url=cached_data.get("linkedin_url"),
                                github_url=cached_data.get("github_url"),
                                location=cached_data.get("location"),
                                skills=cached_data.get("skills", []),
                                experience=[],
                                education=[],
                                summary=cached_data.get("summary"),
                                greenhouse_id=cached_data.get("greenhouse_id"),
                            )
                            resume.experience = cached_data.get("experience", [])
                            resume.education = cached_data.get("education", [])
                            parsed.append(resume)
                            logger.info(
                                "resume_cache_hit",
                                greenhouse_id=metadata.get("greenhouse_id"),
                                email=metadata.get("candidate_email")
                            )
                            continue
                    
                    cache_misses += 1
                    to_parse.append((idx, file_bytes, filename, metadata))
                    
                except Exception as e:
                    failed_count += 1
                    logger.warning(f"Failed to pre-process resume {idx}: {str(e)[:200]}")
            
            logger.info(
                "resume_parsing_phase1_complete",
                cache_hits=cache_hits,
                to_parse=len(to_parse),
                total_resumes=total_resumes,
                max_concurrent=MAX_CONCURRENT_PARSES
            )
            
            # Phase 2: Parse cache misses concurrently
            if to_parse:
                if analysis_id and self.event_callback:
                    self.event_callback(
                        analysis_id,
                        "resume_parsing_progress",
                        f"Parsing {len(to_parse)} resumes ({cache_hits} from cache), up to {MAX_CONCURRENT_PARSES} concurrent",
                        {"cached": cache_hits, "to_parse": len(to_parse), "total": total_resumes, "stage": "parse_resumes"}
                    )
                
                async def _parse_single(idx: int, file_bytes: bytes, filename: str, metadata: dict) -> Optional[ParsedResume]:
                    """Parse a single resume with semaphore-controlled concurrency."""
                    nonlocal completed_count, failed_count
                    
                    async with semaphore:
                        try:
                            resume = await self.resume_parser.parse_resume(
                                file_bytes=file_bytes,
                                filename=filename
                            )
                            
                            # Enrich with source metadata
                            if metadata.get("greenhouse_id"):
                                resume.greenhouse_id = metadata["greenhouse_id"]
                                logger.info(
                                    "greenhouse_id_set_on_resume",
                                    greenhouse_id=resume.greenhouse_id,
                                    candidate_email=resume.email or metadata.get("candidate_email")
                                )
                            if metadata.get("candidate_name") and not resume.full_name:
                                resume.full_name = metadata["candidate_name"]
                            if metadata.get("candidate_email") and not resume.email:
                                resume.email = metadata["candidate_email"]
                            if metadata.get("linkedin_url") and not resume.linkedin_url:
                                resume.linkedin_url = metadata["linkedin_url"]
                            if metadata.get("phone") and not resume.phone:
                                resume.phone = metadata["phone"]
                            if metadata.get("location") and not resume.location:
                                resume.location = metadata["location"]
                            
                            completed_count += 1
                            
                            if analysis_id and self.event_callback:
                                self.event_callback(
                                    analysis_id,
                                    "resume_parsed",
                                    f"Parsed {completed_count}/{len(to_parse)}: {metadata.get('candidate_name') or filename}",
                                    {"current": cache_hits + completed_count, "total": total_resumes, "filename": filename}
                                )
                            
                            return resume
                            
                        except Exception as e:
                            failed_count += 1
                            completed_count += 1
                            logger.warning(
                                "resume_parse_failed",
                                filename=filename,
                                error=str(e),
                                error_type=type(e).__name__
                            )
                            if analysis_id and self.event_callback:
                                self.event_callback(
                                    analysis_id,
                                    "resume_parse_failed",
                                    f"Failed: {metadata.get('candidate_name') or filename} - {str(e)[:100]}",
                                    {"current": cache_hits + completed_count, "total": total_resumes, "error": str(e)[:200]}
                                )
                            return None
                
                # Fire all parse tasks concurrently (semaphore limits actual concurrency)
                parse_tasks = [
                    _parse_single(idx, fb, fn, meta)
                    for idx, fb, fn, meta in to_parse
                ]
                results = await asyncio.gather(*parse_tasks)
                
                for result in results:
                    if result is not None:
                        parsed.append(result)
        
        finally:
            # Rule 16: Always close DB session in finally block
            if db is not None:
                try:
                    db.close()
                except Exception:
                    pass
        
        logger.info(
            "resume_parsing_complete",
            cache_hits=cache_hits,
            cache_misses=cache_misses,
            failed_count=failed_count,
            total_parsed=len(parsed),
            total_attempted=total_resumes
        )
        
        return parsed
    
    async def _score_candidates(
        self,
        candidates: List[ParsedResume],
        diagnostic: DiagnosticReport,
        baseline: BaselineProfile,
        source: CandidateSource
    ) -> List[CandidateScore]:
        """Stage 4/6: Score candidates."""
        scores = []
        failed_count = 0
        
        for idx, candidate in enumerate(candidates):
            try:
                # Convert ParsedResume to dict for scoring engine
                # The scoring engine expects candidate_data as a Dict[str, Any]
                candidate_data = candidate.dict() if hasattr(candidate, 'dict') else candidate.model_dump()
                
                # Generate candidate_id if not present
                candidate_id = getattr(candidate, 'candidate_id', None)
                if not candidate_id:
                    candidate_id = getattr(candidate, 'email', None) or getattr(candidate, 'candidate_name', f"candidate_{idx}")
                
                score = await asyncio.to_thread(
                    self.scoring_engine.score_candidate,
                    candidate_data=candidate_data,
                    baseline=baseline,
                    candidate_source=source,
                    candidate_id=str(candidate_id),
                    diagnostic=diagnostic
                )
                scores.append(score)
            except Exception as e:
                failed_count += 1
                candidate_name = getattr(candidate, 'candidate_name', None) or getattr(candidate, 'full_name', 'unknown')
                candidate_email = getattr(candidate, 'email', None) or 'no_email'
                logger.warning(
                    "candidate_scoring_failed",
                    candidate_name=candidate_name,
                    candidate_email=candidate_email,
                    candidate_index=idx,
                    error=str(e),
                    exc_info=True
                )
        
        if failed_count > 0:
            logger.warning(
                "scoring_completed_with_failures",
                source=source.value,
                total_candidates=len(candidates),
                scored_successfully=len(scores),
                failed_count=failed_count
            )
        
        # Sort by overall score descending
        scores.sort(key=lambda x: x.overall_score, reverse=True)
        
        return scores
    
    async def _search_market(
        self,
        diagnostic: DiagnosticReport,
        baseline: BaselineProfile,
        applicant_scores: List[CandidateScore],
        role: str
    ) -> Tuple[PDLQueryParams, List[ParsedResume]]:
        """Stage 5: Build PDL query and search market."""
        # Build query - use enhanced builder if available (has blueprint/DNA)
        if hasattr(self, 'enhanced_pdl_builder') and self.enhanced_pdl_builder:
            logger.info(
                "using_enhanced_pdl_query_builder",
                has_blueprint=self.blueprint is not None,
                has_dna=self.company_dna is not None
            )
            pdl_query = await asyncio.to_thread(
                self.enhanced_pdl_builder.build_enhanced_query,
                diagnostic=diagnostic,
                baseline=baseline,
                role=role,
                limit=self.pdl_query_limit
            )
        else:
            # Fall back to legacy builder
            pdl_query = await asyncio.to_thread(
                self.pdl_query_builder.build_initial_query,
                diagnostic=diagnostic,
                baseline=baseline,
                role=role,
                limit=self.pdl_query_limit
            )
        
        # Convert to API payload
        api_payload = self.pdl_query_builder.convert_to_pdl_api_payload(pdl_query)
        
        # Call PDL API via connector framework
        # Create a new connector configuration for this specific search query
        try:
            from src.services.ingestion.connectors.people_data_labs import PeopleDataLabsConnector
            from src.services.ingestion.connector_service import ConnectorService
            from src.models.connector import ConnectorConfiguration
            from src.models import database
            import uuid
            
            if database.SessionLocal is None:
                database.init_database()
            
            db = database.SessionLocal()
            try:
                connector_service = ConnectorService(db)
                
                # Get an existing PDL connector to copy credentials from
                # (We need API key from an existing connector)
                existing_pdl_connectors = await asyncio.to_thread(
                    connector_service.list_configurations,
                    customer_id=self.customer_id,
                    connector_type='people_data_labs',
                    is_enabled=True
                )
                
                if not existing_pdl_connectors:
                    raise ValueError("No enabled PDL connector found - need API credentials for market search")
                
                # Use credentials from first enabled connector
                api_credentials = connector_service.get_credentials(existing_pdl_connectors[0])
                
                # Create a new connector configuration for this specific query
                connector_name = f"ML Talent Market Search - {role} - {uuid.uuid4().hex[:8]}"
                # Convert PDLQueryParams to simple dict format for connector config
                # (Connector will handle conversion to Elasticsearch DSL internally)
                # Use empirically validated query format from testing
                simple_query = {}
                
                # Add job_title for specific role matching (preferred for ML engineers)
                if pdl_query.job_title:
                    simple_query["job_title"] = [pdl_query.job_title.lower()]
                
                # Add job_title_role for broad categorization (only if job_title not used)
                if pdl_query.job_title_role and not pdl_query.job_title:
                    simple_query["job_title_role"] = [r.lower() for r in pdl_query.job_title_role]
                
                # Add skills (limit to 5 max per empirical rules)
                all_skills = (pdl_query.required_skills + pdl_query.optional_skills)[:5]
                if all_skills:
                    simple_query["skills"] = [s.lower() for s in all_skills]
                
                # Add location (recommended for credit control)
                simple_query["location_country"] = ["united states"]
                
                # Note: PDL uses inferred_years_experience for experience filtering
                # but it's not a direct filter field in the search API.
                # Experience is better filtered by job_title_levels (e.g., ["senior", "manager"])
                
                new_connector = await asyncio.to_thread(
                    connector_service.create_configuration,
                    customer_id=self.customer_id,
                    connector_type='people_data_labs',
                    connector_name=connector_name,
                    description=f"Market search query for {role} talent intelligence analysis",
                    credentials=api_credentials,
                    sync_config={
                        "search_query": simple_query,
                        "max_records": self.pdl_query_limit,
                        "page_size": self.pdl_query_limit
                    },
                    tags=["ml_talent", "market_search", role.lower().replace(" ", "_")],
                    created_by_user_id=self.user_id
                )
                
                logger.info(
                    "pdl_connector_created",
                    connector_id=new_connector.connector_id,
                    connector_name=connector_name,
                    query_preview=str(simple_query)[:200]
                )
                
                # Initialize PDL connector and fetch results
                pdl_connector = PeopleDataLabsConnector(
                    credentials=api_credentials,
                    config={
                        "search_query": simple_query,
                        "max_records": self.pdl_query_limit,
                        "page_size": self.pdl_query_limit
                    },
                    customer_id=self.customer_id
                )
                
                # Search for candidates matching the profile
                logger.info("calling_pdl_api", query_version=pdl_query.version, limit=self.pdl_query_limit)
                
                # Read results from connector
                results = []
                for batch in await asyncio.to_thread(pdl_connector.read_stream, "full", {}):
                    results.extend(batch)
                    if len(results) >= self.pdl_query_limit:
                        results = results[:self.pdl_query_limit]
                        break
                
                # Log PDL API response for debugging
                logger.info(
                    "pdl_api_response",
                    result_count=len(results) if results else 0,
                    query_used=api_payload.get("query", "")[:200],  # First 200 chars of query
                    sample_result=results[0] if results and len(results) > 0 else None
                )
                
                # Convert PDL results to ParsedResume format for consistency
                market_candidates = []
                for person in results:
                    try:
                        # Extract email - handle both dict and string formats
                        email = person.get('work_email')
                        if not email and person.get('emails'):
                            emails = person.get('emails', [])
                            if emails and len(emails) > 0:
                                first_email = emails[0]
                                if isinstance(first_email, dict):
                                    email = first_email.get('address')
                                elif isinstance(first_email, str):
                                    email = first_email
                        
                        # Extract phone - handle both dict and string formats
                        phone = None
                        phone_numbers = person.get('phone_numbers', [])
                        if phone_numbers and len(phone_numbers) > 0:
                            first_phone = phone_numbers[0]
                            if isinstance(first_phone, dict):
                                phone = first_phone.get('number')
                            elif isinstance(first_phone, str):
                                phone = first_phone
                        
                        # Extract linkedin URL
                        linkedin_url = person.get('linkedin_url')
                        if linkedin_url and not linkedin_url.startswith('http'):
                            linkedin_url = f"https://{linkedin_url}"
                        
                        # Convert PDL person to ParsedResume format
                        # Build experience list from PDL data
                        experience_list = []
                        for job in person.get('experience', [])[:5]:  # Limit to recent 5 jobs
                            company_data = job.get('company', {})
                            title_data = job.get('title', {})
                            experience_list.append(ParsedExperience(
                                company=company_data.get('name') if isinstance(company_data, dict) else company_data,
                                title=title_data.get('name') if isinstance(title_data, dict) else title_data,
                                start_date=job.get('start_date'),
                                end_date=job.get('end_date'),
                                description=None,
                                is_current=job.get('is_primary', False)
                            ))
                        
                        # Build education list from PDL data
                        education_list = []
                        for school in person.get('education', []):
                            school_data = school.get('school', {})
                            education_list.append(ParsedEducation(
                                institution=school_data.get('name') if isinstance(school_data, dict) else school_data,
                                degree=school.get('degrees', [None])[0] if school.get('degrees') else None,
                                field_of_study=school.get('majors', [None])[0] if school.get('majors') else None,
                                start_date=school.get('start_date'),
                                end_date=school.get('end_date')
                            ))
                        
                        parsed = ParsedResume(
                            full_name=person.get('full_name', 'Unknown'),
                            email=email,
                            phone=phone,
                            linkedin_url=linkedin_url,
                            current_title=person.get('job_title'),
                            current_company=person.get('job_company_name'),
                            skills=person.get('skills', []) if isinstance(person.get('skills'), list) else [],
                            experience=experience_list,
                            education=education_list,
                            certifications=[],  # PDL doesn't provide this directly
                            location=person.get('location_name'),
                            parse_confidence=0.95,  # High confidence for PDL data
                            quality_flags=[]  # No quality issues for PDL data
                        )
                        
                        # Store PDL ID in a way we can use later for tracking
                        parsed._pdl_id = f"pdl_{person.get('id', person.get('pdl_id', 'unknown'))}"
                        market_candidates.append(parsed)
                    except Exception as parse_error:
                        logger.warning(
                            "pdl_result_parse_failed",
                            error=str(parse_error),
                            person_id=person.get('id', 'unknown')
                        )
                
                logger.info(
                    "pdl_market_search_complete",
                    query_version=pdl_query.version,
                    candidates_found=len(market_candidates)
                )
                
            finally:
                db.close()
                
        except Exception as e:
            error_str = str(e)
            
            # Check for PDL quota exceeded error
            from src.services.ingestion.connectors.people_data_labs import PDLQuotaExceededError, PDLAuthenticationError
            
            if isinstance(e, PDLQuotaExceededError):
                logger.warning(
                    "pdl_quota_exceeded",
                    error=error_str,
                    query_version=pdl_query.version
                )
                # Emit user-friendly event
                if self.event_callback:
                    self.event_callback(
                        self._current_analysis_id if hasattr(self, '_current_analysis_id') else "unknown",
                        "market_search_quota_exceeded",
                        "Market candidate search skipped: PDL API credits exhausted. "
                        "Please contact your administrator to add more credits. "
                        "Analysis will continue with uploaded/ATS candidates only.",
                        {"error_type": "quota_exceeded", "recoverable": True}
                    )
            elif isinstance(e, PDLAuthenticationError):
                logger.error(
                    "pdl_authentication_failed",
                    error=error_str,
                    query_version=pdl_query.version
                )
                if self.event_callback:
                    self.event_callback(
                        self._current_analysis_id if hasattr(self, '_current_analysis_id') else "unknown",
                        "market_search_auth_failed",
                        "Market candidate search skipped: PDL API authentication failed. "
                        "Please contact your administrator to update API credentials. "
                        "Analysis will continue with uploaded/ATS candidates only.",
                        {"error_type": "auth_failed", "recoverable": True}
                    )
            elif "402" in error_str or "payment_required" in error_str.lower() or "quota" in error_str.lower():
                # Catch any other quota-related errors by string matching
                logger.warning(
                    "pdl_quota_exceeded_generic",
                    error=error_str,
                    query_version=pdl_query.version
                )
                if self.event_callback:
                    self.event_callback(
                        self._current_analysis_id if hasattr(self, '_current_analysis_id') else "unknown",
                        "market_search_quota_exceeded",
                        "Market candidate search skipped: PDL API credits exhausted. "
                        "Analysis will continue with uploaded/ATS candidates only.",
                        {"error_type": "quota_exceeded", "recoverable": True}
                    )
            else:
                logger.error(
                    "pdl_market_search_failed",
                    error=error_str,
                    query_version=pdl_query.version,
                    exc_info=True
                )
                if self.event_callback:
                    self.event_callback(
                        self._current_analysis_id if hasattr(self, '_current_analysis_id') else "unknown",
                        "market_search_failed",
                        f"Market candidate search failed: {error_str[:100]}. "
                        "Analysis will continue with uploaded/ATS candidates only.",
                        {"error_type": "unknown", "recoverable": True}
                    )
            
            # Return empty list on error, don't fail entire analysis
            market_candidates = []
        
        return pdl_query, market_candidates
    
    async def _run_synthesis(
        self,
        diagnostic: DiagnosticReport,
        applicant_scores: List[CandidateScore],
        market_scores: List[CandidateScore],
        top_overall_count: int = 3
    ) -> SynthesisReport:
        """Stage 7: Run synthesis agent."""
        synthesis_agent = SynthesisAgentService(
            customer_id=self.customer_id,
            user_id=self.user_id,
            llm_provider="openai",
            llm_model="gpt-4o-mini"  # Changed from gpt-4o due to quota limits
        )
        
        synthesis_input = SynthesisInput(
            diagnostic_report=diagnostic,
            applicant_scores=applicant_scores,
            market_scores=market_scores,
            top_overall_count=top_overall_count
        )
        
        return await asyncio.to_thread(
            synthesis_agent.synthesize,
            synthesis_input
        )
