"""
Retrieval Celery Tasks.

Async task that runs the RetrievalFlow, persists results to the
retrieval_runs table, saves assistant messages to the conversation,
and auto-generates a conversation title after the first response.
"""

import json
import logging
from datetime import datetime, timezone

import litellm

from src.celery_app import celery_app
from src.flows.retrieval_flow import RetrievalFlow
from src.models import database
from src.models.retrieval import RetrievalRun, RetrievalConversation, RetrievalMessage
from src.core.config import get_settings
from src.services.langfuse_service import get_langfuse_service

logger = logging.getLogger(__name__)

TITLE_SYSTEM = """\
You generate short, catchy conversation titles with a single funky emoji prefix.

Rules:
- Output ONLY the title, nothing else.
- Start with a single relevant emoji.
- Keep the title under 40 characters (including emoji).
- Make it descriptive of the topic, not generic.
- No quotes, no markdown.

Examples:
🔍 CRM Contacts at Acme
🎙️ Last Week's Meetings
💰 Q4 Deal Pipeline
📊 Cengage Partnership Notes
🤝 Heartland Vet Follow-ups
"""


def _generate_title(
    user_query: str,
    answer: str,
    model: str,
    trace_metadata: dict | None = None,
) -> str:
    """Generate a short conversation title with a funky emoji."""
    langfuse_service = get_langfuse_service()
    try:
        with langfuse_service.span_scope(
            name="retrieval.task.generate_title",
            input_data={
                "model": model,
                "user_query": user_query[:500],
                "answer_excerpt": answer[:500],
            },
            metadata={
                **(trace_metadata or {}),
                "component": "agentmesh",
                "flow": "retrieval_task",
                "stage": "generate_title",
            },
        ) as title_span:
            resp = litellm.completion(
                model=model,
                messages=[
                    {"role": "system", "content": TITLE_SYSTEM},
                    {"role": "user", "content": (
                        f"User asked: {user_query}\n\n"
                        f"Answer excerpt: {answer[:500]}\n\n"
                        "Generate a title."
                    )},
                ],
                temperature=0.7,
                max_tokens=60,
            )
            title = resp.choices[0].message.content.strip()
            # Ensure it's not too long
            if len(title) > 60:
                title = title[:57] + "..."

            title_observation = title_span.get("observation")
            if title_observation is not None:
                try:
                    title_observation.update(
                        output={
                            "title": title,
                            "title_length": len(title),
                        }
                    )
                except Exception:
                    pass

            return title
    except Exception as exc:
        logger.warning("Failed to generate title: %s", exc)
        return None


@celery_app.task(bind=True, name="run_retrieval")
def run_retrieval(
    self,
    run_id: str,
    query: str,
    user_id: int,
    customer_id: str,
    conversation_id: str = None,
    workspace_id: int | None = None,
):
    """
    Execute a retrieval flow and persist the results.

    Args:
        run_id:          UUID for this retrieval run (pre-generated by the API).
        query:           User's natural-language search query.
        user_id:         Authenticated user ID.
        customer_id:     Tenant / customer ID.
        conversation_id: Optional conversation to append messages to.
        workspace_id:    Agent Mesh workspace for this retrieval run.
    """
    if database.SessionLocal is None:
        database.init_database()

    langfuse_service = get_langfuse_service()
    trace_metadata = {
        "component": "agentmesh",
        "flow": "retrieval_task",
        "run_id": run_id,
        "customer_id": customer_id,
        "user_id": user_id,
        "conversation_id": conversation_id,
        "workspace_id": workspace_id,
    }

    db = database.SessionLocal()
    try:
        # Mark run as in-progress
        with langfuse_service.span_scope(
            name="retrieval.task.mark_in_progress",
            input_data={"run_id": run_id},
            metadata={**trace_metadata, "stage": "mark_in_progress"},
        ):
            run = db.query(RetrievalRun).filter(RetrievalRun.run_id == run_id).first()
            if run:
                run.status = "retrieving"
                db.commit()

        # Execute the flow
        with langfuse_service.span_scope(
            name="retrieval.task.execute_flow",
            input_data={"query": query},
            metadata={**trace_metadata, "stage": "execute_flow"},
        ) as flow_span_info:
            flow = RetrievalFlow()
            result = flow.run(
                query=query,
                user_id=user_id,
                customer_id=customer_id,
                run_id=run_id,
                conversation_id=conversation_id,
                workspace_id=workspace_id,
            )
            flow_observation = flow_span_info.get("observation")
            if flow_observation is not None:
                try:
                    failed_tool_count = int(result.get("failed_tool_count") or 0)
                    has_error = "error" in result or failed_tool_count > 0
                    flow_output = {
                        "sources": result.get("sources", []),
                        "has_error": has_error,
                        "follow_up_count": len(result.get("follow_ups", []) or []),
                        "failed_tool_count": failed_tool_count,
                        "failed_tools": (result.get("failed_tools") or [])[:10],
                    }
                    if has_error:
                        flow_observation.update(
                            output=flow_output,
                            level="ERROR",
                            status_message=(
                                f"Retrieval flow completed with {failed_tool_count} tool failure(s)"
                                if failed_tool_count > 0
                                else "Retrieval flow returned an error"
                            ),
                        )
                    else:
                        flow_observation.update(output=flow_output)
                except Exception:
                    pass

        # Persist results on the run
        with langfuse_service.span_scope(
            name="retrieval.task.persist_run",
            input_data={"run_id": run_id},
            metadata={**trace_metadata, "stage": "persist_run"},
        ):
            if run:
                run.status = "completed"
                run.results_json = result
                run.sources_used = result.get("sources", [])
                run.completed_at = datetime.now(timezone.utc)
                db.commit()

        # Save assistant message to conversation
        if conversation_id:
            with langfuse_service.span_scope(
                name="retrieval.task.persist_conversation_message",
                input_data={"conversation_id": conversation_id},
                metadata={**trace_metadata, "stage": "persist_conversation_message"},
            ) as message_span:
                answer_text = result.get("raw", "")
                if not answer_text and isinstance(result.get("error"), str):
                    answer_text = result["error"]

                asst_msg = RetrievalMessage(
                    conversation_id=conversation_id,
                    role="assistant",
                    content=answer_text or "No results found.",
                    sources=result.get("sources"),
                    follow_ups=result.get("follow_ups"),
                    run_id=run_id,
                )
                db.add(asst_msg)

                # Update conversation updated_at
                conv = db.query(RetrievalConversation).filter(
                    RetrievalConversation.id == conversation_id
                ).first()
                generated_title = None
                if conv:
                    conv.updated_at = datetime.now(timezone.utc)

                    # Auto-generate title if this is the first response (title is still None)
                    if conv.title is None and answer_text:
                        settings = get_settings()
                        generated_title = _generate_title(
                            query,
                            answer_text,
                            settings.default_llm_model,
                            trace_metadata=trace_metadata,
                        )
                        if generated_title:
                            conv.title = generated_title
                            logger.info("Auto-titled conversation %s: %s", conversation_id, generated_title)

                db.commit()

                message_observation = message_span.get("observation")
                if message_observation is not None:
                    try:
                        message_observation.update(
                            output={
                                "conversation_id": conversation_id,
                                "message_saved": True,
                                "title_generated": bool(generated_title),
                                "follow_up_count": len(result.get("follow_ups", []) or []),
                            }
                        )
                    except Exception:
                        pass

        logger.info("Retrieval run %s completed successfully", run_id)
        return {"run_id": run_id, "status": "completed"}

    except Exception as exc:
        logger.error("Retrieval run %s failed: %s", run_id, exc, exc_info=True)
        langfuse_service.trace_event(
            name="retrieval.task.failed",
            input_data={"run_id": run_id, "conversation_id": conversation_id},
            output_data={"error": str(exc)},
            metadata={**trace_metadata, "stage": "failed"},
        )
        # Mark as failed
        try:
            run = db.query(RetrievalRun).filter(RetrievalRun.run_id == run_id).first()
            if run:
                run.status = "failed"
                run.results_json = {"error": str(exc)}
                run.completed_at = datetime.now(timezone.utc)
                db.commit()

            # Save error message to conversation too
            if conversation_id:
                err_msg = RetrievalMessage(
                    conversation_id=conversation_id,
                    role="assistant",
                    content=f"Search failed: {exc}",
                    run_id=run_id,
                )
                db.add(err_msg)
                db.commit()
        except Exception:
            logger.error("Failed to update run status for %s", run_id)
        raise
    finally:
        db.close()
