"""
Email Templates Models

Section-based email templates with support for both static content
and AI-generated personalized sections.
"""

from sqlalchemy import Column, Integer, String, Boolean, DateTime, Text, JSON, ForeignKey, Index, Enum as SQLEnum
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from typing import Dict, Any, Optional, List
from enum import Enum

from src.models.database import BaseModel


class TemplateSectionType(str, Enum):
    """Types of email template sections."""
    STATIC = "static"  # User-defined static text with variable substitution
    AI_GENERATED = "ai_generated"  # AI-generated personalized content


class TemplateCategory(str, Enum):
    """Email template categories."""
    APPLICANT_FOLLOWUP = "applicant_followup"
    MARKET_OUTREACH = "market_outreach"
    INTERVIEW_INVITE = "interview_invite"
    REJECTION = "rejection"
    CUSTOM = "custom"


class EmailTemplate(BaseModel):
    """
    Email template with section-based content.
    
    Templates can contain multiple sections, each either:
    - Static: Fixed text with variable substitution ({{candidate_name}})
    - AI Generated: Personalized content generated per candidate
    """
    __tablename__ = "email_templates"
    
    # Identity
    customer_id = Column(String(100), ForeignKey("customers.customer_id"), nullable=False, index=True)
    
    # Template metadata
    name = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    category = Column(String(50), nullable=False, default=TemplateCategory.CUSTOM.value)
    
    # Subject line (can contain variables)
    subject = Column(Text, nullable=False)
    subject_is_ai_generated = Column(Boolean, default=False, nullable=False)
    subject_ai_prompt = Column(Text, nullable=True)  # Prompt if AI-generated
    
    # Usage tracking
    use_count = Column(Integer, default=0, nullable=False)
    last_used_at = Column(DateTime(timezone=True), nullable=True)
    
    # Status
    is_active = Column(Boolean, default=True, nullable=False)
    is_default = Column(Boolean, default=False, nullable=False)  # Default template for category
    
    # Relationships
    sections = relationship(
        "EmailTemplateSection", 
        back_populates="template",
        order_by="EmailTemplateSection.section_order",
        cascade="all, delete-orphan"
    )
    
    __table_args__ = (
        Index('ix_email_template_customer', 'customer_id'),
        Index('ix_email_template_category', 'customer_id', 'category'),
        Index('ix_email_template_active', 'customer_id', 'is_active'),
        {'extend_existing': True}
    )
    
    def get_all_variables(self) -> List[str]:
        """Extract all variables used in this template."""
        import re
        variables = set()
        
        # Check subject
        matches = re.findall(r'\{\{(\w+)\}\}', self.subject or '')
        variables.update(matches)
        
        # Check all sections
        for section in self.sections:
            if section.content:
                matches = re.findall(r'\{\{(\w+)\}\}', section.content)
                variables.update(matches)
            if section.ai_prompt:
                matches = re.findall(r'\{\{(\w+)\}\}', section.ai_prompt)
                variables.update(matches)
        
        return sorted(list(variables))


class EmailTemplateSection(BaseModel):
    """
    A section within an email template.
    
    Sections are ordered and can be either:
    - Static: Content is used as-is (with variable substitution)
    - AI Generated: Content is generated by AI using the prompt and context
    """
    __tablename__ = "email_template_sections"
    
    # Parent template
    template_id = Column(Integer, ForeignKey("email_templates.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # Ordering - Python attribute 'section_order' maps to DB column 'order'
    section_order = Column("order", Integer, nullable=False, default=0)
    
    # Section type
    section_type = Column(String(50), nullable=False, default=TemplateSectionType.STATIC.value)
    
    # For static sections: the actual content with variables
    content = Column(Text, nullable=True)
    
    # For AI-generated sections
    ai_prompt = Column(Text, nullable=True)  # e.g., "Write a personalized opening about their skills"
    ai_context_fields = Column(JSON, nullable=True)  # ['candidate_skills', 'job_title', 'company_name']
    ai_tone = Column(String(50), nullable=True, default="professional")  # professional, casual, enthusiastic
    ai_max_length = Column(Integer, nullable=True, default=200)  # Max characters for generated content
    
    # Section metadata
    section_name = Column(String(100), nullable=True)  # e.g., "Opening", "Skills Match", "Call to Action"
    
    # Relationships
    template = relationship("EmailTemplate", back_populates="sections")
    
    __table_args__ = (
        Index('ix_template_section_order', 'template_id', 'order'),
        {'extend_existing': True}
    )


class EmailSectionLibrary(BaseModel):
    """
    Reusable email sections library.
    
    Allows users to save and reuse sections across multiple templates.
    Sections can be tagged and categorized for easy discovery.
    """
    __tablename__ = "email_section_library"
    
    # Identity
    customer_id = Column(String(100), ForeignKey("customers.customer_id"), nullable=False, index=True)
    
    # Section metadata
    name = Column(String(255), nullable=False)  # e.g., "Personalized Skills Opener"
    description = Column(Text, nullable=True)  # Description of when to use this section
    category = Column(String(100), nullable=True)  # e.g., "opening", "skills_match", "call_to_action", "closing"
    tags = Column(JSON, nullable=True)  # e.g., ["technical", "sales", "executive"]
    
    # Section type
    section_type = Column(String(50), nullable=False, default=TemplateSectionType.STATIC.value)
    
    # For static sections: the actual content with variables
    content = Column(Text, nullable=True)
    
    # For AI-generated sections
    ai_prompt = Column(Text, nullable=True)
    ai_context_fields = Column(JSON, nullable=True)
    ai_tone = Column(String(50), nullable=True, default="professional")
    ai_max_length = Column(Integer, nullable=True, default=200)
    
    # Usage tracking
    use_count = Column(Integer, default=0, nullable=False)
    last_used_at = Column(DateTime(timezone=True), nullable=True)
    
    # Status
    is_active = Column(Boolean, default=True, nullable=False)
    is_shared = Column(Boolean, default=False, nullable=False)  # If true, visible to all users in org
    
    # Creator tracking
    created_by_user_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    
    __table_args__ = (
        Index('ix_section_library_customer', 'customer_id'),
        Index('ix_section_library_category', 'customer_id', 'category'),
        Index('ix_section_library_active', 'customer_id', 'is_active'),
        {'extend_existing': True}
    )


class GeneratedEmail(BaseModel):
    """
    Stores generated email content for a specific candidate.
    
    Caches the AI-generated content so we don't regenerate on every view.
    Also allows manual editing before sending.
    """
    __tablename__ = "generated_emails"
    
    # Identity
    customer_id = Column(String(100), ForeignKey("customers.customer_id"), nullable=False, index=True)
    template_id = Column(Integer, ForeignKey("email_templates.id"), nullable=True)
    
    # Candidate reference
    candidate_id = Column(String(255), nullable=False, index=True)  # PDL ID or applicant ID
    talent_analysis_id = Column(String(100), ForeignKey("talent_analyses.analysis_id"), nullable=True)
    
    # Generated content
    subject = Column(Text, nullable=False)
    body = Column(Text, nullable=False)
    
    # Editing tracking
    is_edited = Column(Boolean, default=False, nullable=False)
    original_subject = Column(Text, nullable=True)  # Before any edits
    original_body = Column(Text, nullable=True)  # Before any edits
    
    # Generation metadata
    generation_context = Column(JSON, nullable=True)  # Context used for generation
    generation_model = Column(String(100), nullable=True)  # e.g., "gpt-4"
    
    # Status
    status = Column(String(50), default="draft", nullable=False)  # draft, sent, scheduled
    sent_at = Column(DateTime(timezone=True), nullable=True)
    scheduled_for = Column(DateTime(timezone=True), nullable=True)
    
    __table_args__ = (
        Index('ix_generated_email_candidate', 'customer_id', 'candidate_id'),
        Index('ix_generated_email_analysis', 'talent_analysis_id'),
        {'extend_existing': True}
    )


class PDLQueryCache(BaseModel):
    """
    Caches PDL query results to avoid redundant API calls.
    
    Stores the query hash and resulting person IDs.
    Results are valid for a configurable TTL (default 30 days).
    """
    __tablename__ = "pdl_query_cache"
    
    # Identity
    customer_id = Column(String(100), ForeignKey("customers.customer_id"), nullable=False, index=True)
    
    # Query identification
    query_hash = Column(String(64), nullable=False, index=True)  # SHA256 of normalized query
    query_params = Column(JSON, nullable=False)  # Original query parameters
    query_type = Column(String(50), nullable=False)  # "linkedin_enrichment", "search", "lookalike"
    
    # Results
    result_count = Column(Integer, nullable=False, default=0)
    result_pdl_ids = Column(JSON, nullable=True)  # List of PDL person IDs returned
    
    # Cache metadata
    cache_hit_count = Column(Integer, default=0, nullable=False)  # How many times this cache was used
    last_hit_at = Column(DateTime(timezone=True), nullable=True)
    
    # TTL tracking
    expires_at = Column(DateTime(timezone=True), nullable=False)  # When this cache entry expires
    
    __table_args__ = (
        Index('ix_pdl_cache_query', 'customer_id', 'query_hash'),
        Index('ix_pdl_cache_expires', 'expires_at'),
        {'extend_existing': True}
    )
    
    def is_valid(self) -> bool:
        """Check if cache entry is still valid."""
        from datetime import datetime, timezone
        return datetime.now(timezone.utc) < self.expires_at


class CustomerSettings(BaseModel):
    """
    Customer-specific settings for HR Intelligence features.
    
    Stores configuration like Greenhouse maildrop address, PDL cache TTL, etc.
    """
    __tablename__ = "customer_settings"
    
    # Identity
    customer_id = Column(String(100), ForeignKey("customers.customer_id"), nullable=False, unique=True, index=True)
    
    # Greenhouse settings
    greenhouse_maildrop_address = Column(String(255), nullable=True)  # e.g., maildrop@lily.greenhouse.io
    greenhouse_connector_id = Column(String(100), nullable=True)  # Default Greenhouse connector
    
    # PDL settings
    pdl_cache_ttl_days = Column(Integer, default=30, nullable=False)  # Cache TTL in days
    pdl_max_results_per_query = Column(Integer, default=50, nullable=False)
    
    # Email settings
    default_email_template_id = Column(Integer, ForeignKey("email_templates.id"), nullable=True)
    email_signature = Column(Text, nullable=True)
    sender_name = Column(String(255), nullable=True)
    sender_title = Column(String(255), nullable=True)
    
    # AI settings
    ai_email_generation_enabled = Column(Boolean, default=True, nullable=False)
    ai_model_preference = Column(String(100), default="gpt-4", nullable=False)
    
    __table_args__ = (
        {'extend_existing': True}
    )

